export default function Page() {
  return (
    <div>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
      <p>YOU ARE VISITING HOME PAGE</p>
    </div>
  );
}
